"""
Project Euler Problem 2
=======================

Each new term in the Fibonacci sequence is generated by adding the
previous two terms. By starting with 1 and 2, the first 10 terms will be:

                  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

Find the sum of all the even-valued terms in the sequence which do not
exceed four million.
"""
LIMIT = 4_000_000
fibs = [0,1]
while True:
    current = fibs[-1] + fibs[-2]
    fibs.append(current)
    if current >= LIMIT:
        break
filtered = [x for x in fibs if x%2==0]
print(sum(filtered))
